# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.characterListWidget = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.characterListWidget.sizePolicy().hasHeightForWidth())
        self.characterListWidget.setSizePolicy(sizePolicy)
        self.characterListWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.characterListWidget.setObjectName("characterListWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.sexField = QtWidgets.QLineEdit(self.tab)
        self.sexField.setReadOnly(True)
        self.sexField.setObjectName("sexField")
        self.gridLayout_3.addWidget(self.sexField, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)
        self.ageField = QtWidgets.QLineEdit(self.tab)
        self.ageField.setReadOnly(True)
        self.ageField.setObjectName("ageField")
        self.gridLayout_3.addWidget(self.ageField, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 7, 0, 1, 1)
        self.nameField = QtWidgets.QLineEdit(self.tab)
        self.nameField.setReadOnly(True)
        self.nameField.setObjectName("nameField")
        self.gridLayout_3.addWidget(self.nameField, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 8, 0, 1, 1)
        self.raceField = QtWidgets.QLineEdit(self.tab)
        self.raceField.setReadOnly(True)
        self.raceField.setObjectName("raceField")
        self.gridLayout_3.addWidget(self.raceField, 3, 1, 1, 1)
        self.eyesField = QtWidgets.QLineEdit(self.tab)
        self.eyesField.setReadOnly(True)
        self.eyesField.setObjectName("eyesField")
        self.gridLayout_3.addWidget(self.eyesField, 4, 1, 1, 1)
        self.hairField = QtWidgets.QLineEdit(self.tab)
        self.hairField.setReadOnly(True)
        self.hairField.setObjectName("hairField")
        self.gridLayout_3.addWidget(self.hairField, 5, 1, 1, 1)
        self.heightField = QtWidgets.QLineEdit(self.tab)
        self.heightField.setReadOnly(True)
        self.heightField.setObjectName("heightField")
        self.gridLayout_3.addWidget(self.heightField, 6, 1, 1, 1)
        self.weightField = QtWidgets.QLineEdit(self.tab)
        self.weightField.setReadOnly(True)
        self.weightField.setObjectName("weightField")
        self.gridLayout_3.addWidget(self.weightField, 7, 1, 1, 1)
        self.appearanceField = QtWidgets.QTextEdit(self.tab)
        self.appearanceField.setReadOnly(True)
        self.appearanceField.setObjectName("appearanceField")
        self.gridLayout_3.addWidget(self.appearanceField, 8, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 131, 199))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.strengthSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.strengthSpinBox.setObjectName("strengthSpinBox")
        self.gridLayout_2.addWidget(self.strengthSpinBox, 0, 1, 1, 1)
        self.enduranceBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.enduranceBox.setObjectName("enduranceBox")
        self.gridLayout_2.addWidget(self.enduranceBox, 2, 1, 1, 1)
        self.charismaBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.charismaBox.setObjectName("charismaBox")
        self.gridLayout_2.addWidget(self.charismaBox, 3, 1, 1, 1)
        self.intelligenceBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.intelligenceBox.setObjectName("intelligenceBox")
        self.gridLayout_2.addWidget(self.intelligenceBox, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.agilityBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.agilityBox.setObjectName("agilityBox")
        self.gridLayout_2.addWidget(self.agilityBox, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.perceptionBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.perceptionBox.setObjectName("perceptionBox")
        self.gridLayout_2.addWidget(self.perceptionBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.luckBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.luckBox.setObjectName("luckBox")
        self.gridLayout_2.addWidget(self.luckBox, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 311, 561))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 11, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 13, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 15, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.bigGunsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.bigGunsBox.setObjectName("bigGunsBox")
        self.gridLayout_4.addWidget(self.bigGunsBox, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 5, 0, 1, 1)
        self.smallGunsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.smallGunsBox.setObjectName("smallGunsBox")
        self.gridLayout_4.addWidget(self.smallGunsBox, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 12, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 14, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 16, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 8, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 10, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 17, 0, 1, 1)
        self.energyWeaponsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.energyWeaponsBox.setObjectName("energyWeaponsBox")
        self.gridLayout_4.addWidget(self.energyWeaponsBox, 2, 1, 1, 1)
        self.unarmedBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.unarmedBox.setObjectName("unarmedBox")
        self.gridLayout_4.addWidget(self.unarmedBox, 3, 1, 1, 1)
        self.meleeWeaponsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.meleeWeaponsBox.setObjectName("meleeWeaponsBox")
        self.gridLayout_4.addWidget(self.meleeWeaponsBox, 4, 1, 1, 1)
        self.throwingBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.throwingBox.setObjectName("throwingBox")
        self.gridLayout_4.addWidget(self.throwingBox, 5, 1, 1, 1)
        self.explosivesBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.explosivesBox.setObjectName("explosivesBox")
        self.gridLayout_4.addWidget(self.explosivesBox, 6, 1, 1, 1)
        self.doctorBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.doctorBox.setObjectName("doctorBox")
        self.gridLayout_4.addWidget(self.doctorBox, 7, 1, 1, 1)
        self.sneakBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sneakBox.setObjectName("sneakBox")
        self.gridLayout_4.addWidget(self.sneakBox, 8, 1, 1, 1)
        self.lockpickBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.lockpickBox.setObjectName("lockpickBox")
        self.gridLayout_4.addWidget(self.lockpickBox, 9, 1, 1, 1)
        self.trapsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.trapsBox.setObjectName("trapsBox")
        self.gridLayout_4.addWidget(self.trapsBox, 10, 1, 1, 1)
        self.scienceBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.scienceBox.setObjectName("scienceBox")
        self.gridLayout_4.addWidget(self.scienceBox, 11, 1, 1, 1)
        self.repairBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.repairBox.setObjectName("repairBox")
        self.gridLayout_4.addWidget(self.repairBox, 12, 1, 1, 1)
        self.pilotBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.pilotBox.setObjectName("pilotBox")
        self.gridLayout_4.addWidget(self.pilotBox, 13, 1, 1, 1)
        self.speechBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.speechBox.setObjectName("speechBox")
        self.gridLayout_4.addWidget(self.speechBox, 14, 1, 1, 1)
        self.barterBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.barterBox.setObjectName("barterBox")
        self.gridLayout_4.addWidget(self.barterBox, 15, 1, 1, 1)
        self.gamblingBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.gamblingBox.setObjectName("gamblingBox")
        self.gridLayout_4.addWidget(self.gamblingBox, 16, 1, 1, 1)
        self.survivalBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.survivalBox.setObjectName("survivalBox")
        self.gridLayout_4.addWidget(self.survivalBox, 17, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.quitAction = QtWidgets.QAction(MainWindow)
        self.quitAction.setObjectName("quitAction")
        self.saveCharacterAction = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/themes/oxygen/22x22/actions/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.saveCharacterAction.setIcon(icon)
        self.saveCharacterAction.setObjectName("saveCharacterAction")
        self.newCharacterAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/themes/oxygen/22x22/actions/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.newCharacterAction.setIcon(icon1)
        self.newCharacterAction.setObjectName("newCharacterAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.openCharacterAction = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/themes/oxygen/22x22/actions/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openCharacterAction.setIcon(icon2)
        self.openCharacterAction.setObjectName("openCharacterAction")
        self.exportCharacterAction = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/themes/oxygen/22x22/actions/document-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportCharacterAction.setIcon(icon3)
        self.exportCharacterAction.setObjectName("exportCharacterAction")
        self.importCharacterAction = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/themes/oxygen/22x22/actions/document-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importCharacterAction.setIcon(icon4)
        self.importCharacterAction.setObjectName("importCharacterAction")
        self.menuFile.addAction(self.quitAction)
        self.menuHelp.addAction(self.aboutAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.newCharacterAction)
        self.toolBar.addAction(self.saveCharacterAction)
        self.toolBar.addAction(self.openCharacterAction)
        self.toolBar.addAction(self.exportCharacterAction)
        self.toolBar.addAction(self.importCharacterAction)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fallout PnP Character Creator"))
        self.label_8.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "Sex"))
        self.label_12.setText(_translate("MainWindow", "Eyes"))
        self.label_9.setText(_translate("MainWindow", "Age"))
        self.label_14.setText(_translate("MainWindow", "Height"))
        self.label_13.setText(_translate("MainWindow", "Hair"))
        self.label_15.setText(_translate("MainWindow", "Weigth"))
        self.label_11.setText(_translate("MainWindow", "Race"))
        self.label_16.setText(_translate("MainWindow", "Appearance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General"))
        self.label.setText(_translate("MainWindow", "Strength"))
        self.label_4.setText(_translate("MainWindow", "Agility"))
        self.label_5.setText(_translate("MainWindow", "Charisma"))
        self.label_6.setText(_translate("MainWindow", "Intelligence"))
        self.label_7.setText(_translate("MainWindow", "Luck"))
        self.label_2.setText(_translate("MainWindow", "Perception"))
        self.label_3.setText(_translate("MainWindow", "Endurance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "S.P.E.C.I.A.L."))
        self.label_28.setText(_translate("MainWindow", "Science"))
        self.label_26.setText(_translate("MainWindow", "Lockpick"))
        self.label_24.setText(_translate("MainWindow", "Doctor"))
        self.label_20.setText(_translate("MainWindow", "Unarmed"))
        self.label_30.setText(_translate("MainWindow", "Pilot"))
        self.label_32.setText(_translate("MainWindow", "Barter"))
        self.label_18.setText(_translate("MainWindow", "Big Guns"))
        self.label_22.setText(_translate("MainWindow", "Throwing"))
        self.label_17.setText(_translate("MainWindow", "Small Guns"))
        self.label_29.setText(_translate("MainWindow", "Repair"))
        self.label_31.setText(_translate("MainWindow", "Speech"))
        self.label_33.setText(_translate("MainWindow", "Gambling"))
        self.label_25.setText(_translate("MainWindow", "Sneak"))
        self.label_19.setText(_translate("MainWindow", "Energy Weapons"))
        self.label_23.setText(_translate("MainWindow", "Explosives"))
        self.label_27.setText(_translate("MainWindow", "Traps"))
        self.label_21.setText(_translate("MainWindow", "Melee Weapons"))
        self.label_34.setText(_translate("MainWindow", "Survival"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Skills"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.quitAction.setText(_translate("MainWindow", "&Quit"))
        self.quitAction.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.saveCharacterAction.setText(_translate("MainWindow", "Save"))
        self.saveCharacterAction.setToolTip(_translate("MainWindow", "Save Character"))
        self.saveCharacterAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.newCharacterAction.setText(_translate("MainWindow", "New"))
        self.newCharacterAction.setToolTip(_translate("MainWindow", "New Character"))
        self.newCharacterAction.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.aboutAction.setText(_translate("MainWindow", "&About"))
        self.openCharacterAction.setText(_translate("MainWindow", "openCharacter"))
        self.openCharacterAction.setToolTip(_translate("MainWindow", "Open"))
        self.openCharacterAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.exportCharacterAction.setText(_translate("MainWindow", "exportCharacter"))
        self.exportCharacterAction.setToolTip(_translate("MainWindow", "Export the current character"))
        self.exportCharacterAction.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.importCharacterAction.setText(_translate("MainWindow", "importCharacter"))
        self.importCharacterAction.setToolTip(_translate("MainWindow", "Import a character"))
        self.importCharacterAction.setShortcut(_translate("MainWindow", "Ctrl+I"))

import oxygen_rc
