# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\new_character_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 628)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.page)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 6, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.page)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 8, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 198))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.strengthSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.strengthSpinBox.setObjectName("strengthSpinBox")
        self.gridLayout_4.addWidget(self.strengthSpinBox, 0, 1, 1, 1)
        self.enduranceBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.enduranceBox.setObjectName("enduranceBox")
        self.gridLayout_4.addWidget(self.enduranceBox, 2, 1, 1, 1)
        self.charismaBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.charismaBox.setObjectName("charismaBox")
        self.gridLayout_4.addWidget(self.charismaBox, 3, 1, 1, 1)
        self.intelligenceBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.intelligenceBox.setObjectName("intelligenceBox")
        self.gridLayout_4.addWidget(self.intelligenceBox, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 4, 0, 1, 1)
        self.agilityBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.agilityBox.setObjectName("agilityBox")
        self.gridLayout_4.addWidget(self.agilityBox, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.perceptionBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.perceptionBox.setObjectName("perceptionBox")
        self.gridLayout_4.addWidget(self.perceptionBox, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.luckBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.luckBox.setObjectName("luckBox")
        self.gridLayout_4.addWidget(self.luckBox, 6, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 311, 561))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 11, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 13, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 15, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 0, 1, 1)
        self.bigGunsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.bigGunsBox.setObjectName("bigGunsBox")
        self.gridLayout_5.addWidget(self.bigGunsBox, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 5, 0, 1, 1)
        self.smallGunsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.smallGunsBox.setObjectName("smallGunsBox")
        self.gridLayout_5.addWidget(self.smallGunsBox, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 12, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 14, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 16, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 8, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 10, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 17, 0, 1, 1)
        self.energyWeaponsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.energyWeaponsBox.setObjectName("energyWeaponsBox")
        self.gridLayout_5.addWidget(self.energyWeaponsBox, 2, 1, 1, 1)
        self.unarmedBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.unarmedBox.setObjectName("unarmedBox")
        self.gridLayout_5.addWidget(self.unarmedBox, 3, 1, 1, 1)
        self.meleeWeaponsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.meleeWeaponsBox.setObjectName("meleeWeaponsBox")
        self.gridLayout_5.addWidget(self.meleeWeaponsBox, 4, 1, 1, 1)
        self.throwingBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.throwingBox.setObjectName("throwingBox")
        self.gridLayout_5.addWidget(self.throwingBox, 5, 1, 1, 1)
        self.explosivesBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.explosivesBox.setObjectName("explosivesBox")
        self.gridLayout_5.addWidget(self.explosivesBox, 6, 1, 1, 1)
        self.doctorBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.doctorBox.setObjectName("doctorBox")
        self.gridLayout_5.addWidget(self.doctorBox, 7, 1, 1, 1)
        self.sneakBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sneakBox.setObjectName("sneakBox")
        self.gridLayout_5.addWidget(self.sneakBox, 8, 1, 1, 1)
        self.lockpickBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.lockpickBox.setObjectName("lockpickBox")
        self.gridLayout_5.addWidget(self.lockpickBox, 9, 1, 1, 1)
        self.trapsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.trapsBox.setObjectName("trapsBox")
        self.gridLayout_5.addWidget(self.trapsBox, 10, 1, 1, 1)
        self.scienceBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.scienceBox.setObjectName("scienceBox")
        self.gridLayout_5.addWidget(self.scienceBox, 11, 1, 1, 1)
        self.repairBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.repairBox.setObjectName("repairBox")
        self.gridLayout_5.addWidget(self.repairBox, 12, 1, 1, 1)
        self.pilotBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.pilotBox.setObjectName("pilotBox")
        self.gridLayout_5.addWidget(self.pilotBox, 13, 1, 1, 1)
        self.speechBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.speechBox.setObjectName("speechBox")
        self.gridLayout_5.addWidget(self.speechBox, 14, 1, 1, 1)
        self.barterBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.barterBox.setObjectName("barterBox")
        self.gridLayout_5.addWidget(self.barterBox, 15, 1, 1, 1)
        self.gamblingBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.gamblingBox.setObjectName("gamblingBox")
        self.gridLayout_5.addWidget(self.gamblingBox, 16, 1, 1, 1)
        self.survivalBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.survivalBox.setObjectName("survivalBox")
        self.gridLayout_5.addWidget(self.survivalBox, 17, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name"))
        self.comboBox.setItemText(0, _translate("Dialog", "Human"))
        self.comboBox.setItemText(1, _translate("Dialog", "Ghoul"))
        self.comboBox.setItemText(2, _translate("Dialog", "Super Mutant"))
        self.comboBox.setItemText(3, _translate("Dialog", "Half Mutant"))
        self.comboBox.setItemText(4, _translate("Dialog", "Deathclaw"))
        self.comboBox.setItemText(5, _translate("Dialog", "Dog"))
        self.comboBox.setItemText(6, _translate("Dialog", "Robot"))
        self.label_2.setText(_translate("Dialog", "Age"))
        self.label_3.setText(_translate("Dialog", "Sex"))
        self.label_4.setText(_translate("Dialog", "Race"))
        self.label_8.setText(_translate("Dialog", "Weight"))
        self.label_5.setText(_translate("Dialog", "Eyes"))
        self.label_7.setText(_translate("Dialog", "Height"))
        self.label_6.setText(_translate("Dialog", "Hair"))
        self.label_9.setText(_translate("Dialog", "Appearance"))
        self.label_10.setText(_translate("Dialog", "Strength"))
        self.label_11.setText(_translate("Dialog", "Agility"))
        self.label_12.setText(_translate("Dialog", "Charisma"))
        self.label_13.setText(_translate("Dialog", "Intelligence"))
        self.label_14.setText(_translate("Dialog", "Luck"))
        self.label_15.setText(_translate("Dialog", "Perception"))
        self.label_16.setText(_translate("Dialog", "Endurance"))
        self.label_28.setText(_translate("Dialog", "Science"))
        self.label_26.setText(_translate("Dialog", "Lockpick"))
        self.label_24.setText(_translate("Dialog", "Doctor"))
        self.label_20.setText(_translate("Dialog", "Unarmed"))
        self.label_30.setText(_translate("Dialog", "Pilot"))
        self.label_32.setText(_translate("Dialog", "Barter"))
        self.label_18.setText(_translate("Dialog", "Big Guns"))
        self.label_22.setText(_translate("Dialog", "Throwing"))
        self.label_17.setText(_translate("Dialog", "Small Guns"))
        self.label_29.setText(_translate("Dialog", "Repair"))
        self.label_31.setText(_translate("Dialog", "Speech"))
        self.label_33.setText(_translate("Dialog", "Gambling"))
        self.label_25.setText(_translate("Dialog", "Sneak"))
        self.label_19.setText(_translate("Dialog", "Energy Weapons"))
        self.label_23.setText(_translate("Dialog", "Explosives"))
        self.label_27.setText(_translate("Dialog", "Traps"))
        self.label_21.setText(_translate("Dialog", "Melee Weapons"))
        self.label_34.setText(_translate("Dialog", "Survival"))

