# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/new_character_dialogue.ui'
#
# Created: Sat Aug 20 17:34:16 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 628)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.racePicker = QtWidgets.QComboBox(self.page)
        self.racePicker.setObjectName("racePicker")
        self.racePicker.addItem("")
        self.racePicker.addItem("")
        self.racePicker.addItem("")
        self.racePicker.addItem("")
        self.racePicker.addItem("")
        self.racePicker.addItem("")
        self.racePicker.addItem("")
        self.gridLayout_2.addWidget(self.racePicker, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.nameField = QtWidgets.QLineEdit(self.page)
        self.nameField.setObjectName("nameField")
        self.gridLayout_2.addWidget(self.nameField, 0, 1, 1, 1)
        self.ageField = QtWidgets.QLineEdit(self.page)
        self.ageField.setObjectName("ageField")
        self.gridLayout_2.addWidget(self.ageField, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.eyesField = QtWidgets.QLineEdit(self.page)
        self.eyesField.setObjectName("eyesField")
        self.gridLayout_2.addWidget(self.eyesField, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.hairField = QtWidgets.QLineEdit(self.page)
        self.hairField.setObjectName("hairField")
        self.gridLayout_2.addWidget(self.hairField, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.heightField = QtWidgets.QLineEdit(self.page)
        self.heightField.setObjectName("heightField")
        self.gridLayout_2.addWidget(self.heightField, 6, 1, 1, 1)
        self.weightField = QtWidgets.QLineEdit(self.page)
        self.weightField.setObjectName("weightField")
        self.gridLayout_2.addWidget(self.weightField, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 1)
        self.appearanceField = QtWidgets.QTextEdit(self.page)
        self.appearanceField.setObjectName("appearanceField")
        self.gridLayout_2.addWidget(self.appearanceField, 8, 1, 1, 1)
        self.sexPicker = QtWidgets.QComboBox(self.page)
        self.sexPicker.setObjectName("sexPicker")
        self.gridLayout_2.addWidget(self.sexPicker, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 155, 294))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.intelligenceBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.intelligenceBox.setObjectName("intelligenceBox")
        self.gridLayout_4.addWidget(self.intelligenceBox, 4, 1, 1, 1)
        self.strengthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.strengthLabel.setObjectName("strengthLabel")
        self.gridLayout_4.addWidget(self.strengthLabel, 0, 0, 1, 1)
        self.agilityLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.agilityLabel.setObjectName("agilityLabel")
        self.gridLayout_4.addWidget(self.agilityLabel, 5, 0, 1, 1)
        self.strengthSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.strengthSpinBox.setObjectName("strengthSpinBox")
        self.gridLayout_4.addWidget(self.strengthSpinBox, 0, 1, 1, 1)
        self.charismaLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.charismaLabel.setObjectName("charismaLabel")
        self.gridLayout_4.addWidget(self.charismaLabel, 3, 0, 1, 1)
        self.luckLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.luckLabel.setObjectName("luckLabel")
        self.gridLayout_4.addWidget(self.luckLabel, 6, 0, 1, 1)
        self.intelligenceLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.intelligenceLabel.setObjectName("intelligenceLabel")
        self.gridLayout_4.addWidget(self.intelligenceLabel, 4, 0, 1, 1)
        self.charismaBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.charismaBox.setObjectName("charismaBox")
        self.gridLayout_4.addWidget(self.charismaBox, 3, 1, 1, 1)
        self.luckBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.luckBox.setObjectName("luckBox")
        self.gridLayout_4.addWidget(self.luckBox, 6, 1, 1, 1)
        self.enduranceLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.enduranceLabel.setObjectName("enduranceLabel")
        self.gridLayout_4.addWidget(self.enduranceLabel, 2, 0, 1, 1)
        self.perceptionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.perceptionLabel.setObjectName("perceptionLabel")
        self.gridLayout_4.addWidget(self.perceptionLabel, 1, 0, 1, 1)
        self.agilityBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.agilityBox.setObjectName("agilityBox")
        self.gridLayout_4.addWidget(self.agilityBox, 5, 1, 1, 1)
        self.perceptionBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.perceptionBox.setObjectName("perceptionBox")
        self.gridLayout_4.addWidget(self.perceptionBox, 1, 1, 1, 1)
        self.enduranceBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.enduranceBox.setObjectName("enduranceBox")
        self.gridLayout_4.addWidget(self.enduranceBox, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 7, 0, 1, 1)
        self.availablePointsBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.availablePointsBox.setReadOnly(True)
        self.availablePointsBox.setObjectName("availablePointsBox")
        self.gridLayout_4.addWidget(self.availablePointsBox, 7, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 191, 561))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.speechLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.speechLabel.setObjectName("speechLabel")
        self.gridLayout_5.addWidget(self.speechLabel, 14, 0, 1, 1)
        self.explosivesBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.explosivesBox.setObjectName("explosivesBox")
        self.gridLayout_5.addWidget(self.explosivesBox, 6, 1, 1, 1)
        self.meleeWeaponsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.meleeWeaponsBox.setObjectName("meleeWeaponsBox")
        self.gridLayout_5.addWidget(self.meleeWeaponsBox, 4, 1, 1, 1)
        self.energyWeaponsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.energyWeaponsBox.setObjectName("energyWeaponsBox")
        self.gridLayout_5.addWidget(self.energyWeaponsBox, 2, 1, 1, 1)
        self.unarmedLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.unarmedLabel.setObjectName("unarmedLabel")
        self.gridLayout_5.addWidget(self.unarmedLabel, 3, 0, 1, 1)
        self.sneakBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sneakBox.setObjectName("sneakBox")
        self.gridLayout_5.addWidget(self.sneakBox, 8, 1, 1, 1)
        self.repairLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.repairLabel.setObjectName("repairLabel")
        self.gridLayout_5.addWidget(self.repairLabel, 12, 0, 1, 1)
        self.throwingLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.throwingLabel.setObjectName("throwingLabel")
        self.gridLayout_5.addWidget(self.throwingLabel, 5, 0, 1, 1)
        self.pilotLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.pilotLabel.setObjectName("pilotLabel")
        self.gridLayout_5.addWidget(self.pilotLabel, 13, 0, 1, 1)
        self.gamblingLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.gamblingLabel.setObjectName("gamblingLabel")
        self.gridLayout_5.addWidget(self.gamblingLabel, 16, 0, 1, 1)
        self.unarmedBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.unarmedBox.setObjectName("unarmedBox")
        self.gridLayout_5.addWidget(self.unarmedBox, 3, 1, 1, 1)
        self.lockpickBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.lockpickBox.setObjectName("lockpickBox")
        self.gridLayout_5.addWidget(self.lockpickBox, 9, 1, 1, 1)
        self.smallGunsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.smallGunsLabel.setObjectName("smallGunsLabel")
        self.gridLayout_5.addWidget(self.smallGunsLabel, 0, 0, 1, 1)
        self.survivalBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.survivalBox.setObjectName("survivalBox")
        self.gridLayout_5.addWidget(self.survivalBox, 17, 1, 1, 1)
        self.bigGunsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.bigGunsLabel.setObjectName("bigGunsLabel")
        self.gridLayout_5.addWidget(self.bigGunsLabel, 1, 0, 1, 1)
        self.bigGunsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.bigGunsBox.setObjectName("bigGunsBox")
        self.gridLayout_5.addWidget(self.bigGunsBox, 1, 1, 1, 1)
        self.doctorBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.doctorBox.setObjectName("doctorBox")
        self.gridLayout_5.addWidget(self.doctorBox, 7, 1, 1, 1)
        self.throwingBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.throwingBox.setObjectName("throwingBox")
        self.gridLayout_5.addWidget(self.throwingBox, 5, 1, 1, 1)
        self.trapsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.trapsLabel.setObjectName("trapsLabel")
        self.gridLayout_5.addWidget(self.trapsLabel, 10, 0, 1, 1)
        self.barterLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.barterLabel.setObjectName("barterLabel")
        self.gridLayout_5.addWidget(self.barterLabel, 15, 0, 1, 1)
        self.smallGunsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.smallGunsBox.setObjectName("smallGunsBox")
        self.gridLayout_5.addWidget(self.smallGunsBox, 0, 1, 1, 1)
        self.explosivesLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.explosivesLabel.setObjectName("explosivesLabel")
        self.gridLayout_5.addWidget(self.explosivesLabel, 6, 0, 1, 1)
        self.energyWeaponsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.energyWeaponsLabel.setObjectName("energyWeaponsLabel")
        self.gridLayout_5.addWidget(self.energyWeaponsLabel, 2, 0, 1, 1)
        self.sneakLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.sneakLabel.setObjectName("sneakLabel")
        self.gridLayout_5.addWidget(self.sneakLabel, 8, 0, 1, 1)
        self.meleeWeaponsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.meleeWeaponsLabel.setObjectName("meleeWeaponsLabel")
        self.gridLayout_5.addWidget(self.meleeWeaponsLabel, 4, 0, 1, 1)
        self.barterBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.barterBox.setObjectName("barterBox")
        self.gridLayout_5.addWidget(self.barterBox, 15, 1, 1, 1)
        self.pilotBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.pilotBox.setObjectName("pilotBox")
        self.gridLayout_5.addWidget(self.pilotBox, 13, 1, 1, 1)
        self.gamblingBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.gamblingBox.setObjectName("gamblingBox")
        self.gridLayout_5.addWidget(self.gamblingBox, 16, 1, 1, 1)
        self.speechBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.speechBox.setObjectName("speechBox")
        self.gridLayout_5.addWidget(self.speechBox, 14, 1, 1, 1)
        self.lockpickLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lockpickLabel.setObjectName("lockpickLabel")
        self.gridLayout_5.addWidget(self.lockpickLabel, 9, 0, 1, 1)
        self.survivalLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.survivalLabel.setObjectName("survivalLabel")
        self.gridLayout_5.addWidget(self.survivalLabel, 17, 0, 1, 1)
        self.trapsBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.trapsBox.setObjectName("trapsBox")
        self.gridLayout_5.addWidget(self.trapsBox, 10, 1, 1, 1)
        self.doctorLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.doctorLabel.setObjectName("doctorLabel")
        self.gridLayout_5.addWidget(self.doctorLabel, 7, 0, 1, 1)
        self.repairBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.repairBox.setObjectName("repairBox")
        self.gridLayout_5.addWidget(self.repairBox, 12, 1, 1, 1)
        self.scienceLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scienceLabel.setObjectName("scienceLabel")
        self.gridLayout_5.addWidget(self.scienceLabel, 11, 0, 1, 1)
        self.scienceBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.scienceBox.setObjectName("scienceBox")
        self.gridLayout_5.addWidget(self.scienceBox, 11, 1, 1, 1)
        self.smallGunsTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.smallGunsTag.setText("")
        self.smallGunsTag.setObjectName("smallGunsTag")
        self.gridLayout_5.addWidget(self.smallGunsTag, 0, 2, 1, 1)
        self.bigGunsTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.bigGunsTag.setText("")
        self.bigGunsTag.setObjectName("bigGunsTag")
        self.gridLayout_5.addWidget(self.bigGunsTag, 1, 2, 1, 1)
        self.energyWeaponsTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.energyWeaponsTag.setText("")
        self.energyWeaponsTag.setObjectName("energyWeaponsTag")
        self.gridLayout_5.addWidget(self.energyWeaponsTag, 2, 2, 1, 1)
        self.unarmedTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.unarmedTag.setText("")
        self.unarmedTag.setObjectName("unarmedTag")
        self.gridLayout_5.addWidget(self.unarmedTag, 3, 2, 1, 1)
        self.meleeWeaponsTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.meleeWeaponsTag.setText("")
        self.meleeWeaponsTag.setObjectName("meleeWeaponsTag")
        self.gridLayout_5.addWidget(self.meleeWeaponsTag, 4, 2, 1, 1)
        self.throwingTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.throwingTag.setText("")
        self.throwingTag.setObjectName("throwingTag")
        self.gridLayout_5.addWidget(self.throwingTag, 5, 2, 1, 1)
        self.explosivesTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.explosivesTag.setText("")
        self.explosivesTag.setObjectName("explosivesTag")
        self.gridLayout_5.addWidget(self.explosivesTag, 6, 2, 1, 1)
        self.doctorTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.doctorTag.setText("")
        self.doctorTag.setObjectName("doctorTag")
        self.gridLayout_5.addWidget(self.doctorTag, 7, 2, 1, 1)
        self.sneakTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.sneakTag.setText("")
        self.sneakTag.setObjectName("sneakTag")
        self.gridLayout_5.addWidget(self.sneakTag, 8, 2, 1, 1)
        self.lockpickTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.lockpickTag.setText("")
        self.lockpickTag.setObjectName("lockpickTag")
        self.gridLayout_5.addWidget(self.lockpickTag, 9, 2, 1, 1)
        self.trapsTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.trapsTag.setText("")
        self.trapsTag.setObjectName("trapsTag")
        self.gridLayout_5.addWidget(self.trapsTag, 10, 2, 1, 1)
        self.scienceTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.scienceTag.setText("")
        self.scienceTag.setObjectName("scienceTag")
        self.gridLayout_5.addWidget(self.scienceTag, 11, 2, 1, 1)
        self.repairTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.repairTag.setText("")
        self.repairTag.setObjectName("repairTag")
        self.gridLayout_5.addWidget(self.repairTag, 12, 2, 1, 1)
        self.pilotTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.pilotTag.setText("")
        self.pilotTag.setObjectName("pilotTag")
        self.gridLayout_5.addWidget(self.pilotTag, 13, 2, 1, 1)
        self.speechTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.speechTag.setText("")
        self.speechTag.setObjectName("speechTag")
        self.gridLayout_5.addWidget(self.speechTag, 14, 2, 1, 1)
        self.barterTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.barterTag.setText("")
        self.barterTag.setObjectName("barterTag")
        self.gridLayout_5.addWidget(self.barterTag, 15, 2, 1, 1)
        self.gamblingTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.gamblingTag.setText("")
        self.gamblingTag.setObjectName("gamblingTag")
        self.gridLayout_5.addWidget(self.gamblingTag, 16, 2, 1, 1)
        self.survivalTag = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.survivalTag.setText("")
        self.survivalTag.setObjectName("survivalTag")
        self.gridLayout_5.addWidget(self.survivalTag, 17, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name"))
        self.racePicker.setItemText(0, _translate("Dialog", "Human"))
        self.racePicker.setItemText(1, _translate("Dialog", "Ghoul"))
        self.racePicker.setItemText(2, _translate("Dialog", "Super Mutant"))
        self.racePicker.setItemText(3, _translate("Dialog", "Half Mutant"))
        self.racePicker.setItemText(4, _translate("Dialog", "Deathclaw"))
        self.racePicker.setItemText(5, _translate("Dialog", "Dog"))
        self.racePicker.setItemText(6, _translate("Dialog", "Robot"))
        self.label_2.setText(_translate("Dialog", "Age"))
        self.label_3.setText(_translate("Dialog", "Sex"))
        self.label_4.setText(_translate("Dialog", "Race"))
        self.label_8.setText(_translate("Dialog", "Weight"))
        self.label_5.setText(_translate("Dialog", "Eyes"))
        self.label_7.setText(_translate("Dialog", "Height"))
        self.label_6.setText(_translate("Dialog", "Hair"))
        self.label_9.setText(_translate("Dialog", "Appearance"))
        self.strengthLabel.setText(_translate("Dialog", "Strength"))
        self.agilityLabel.setText(_translate("Dialog", "Agility"))
        self.charismaLabel.setText(_translate("Dialog", "Charisma"))
        self.luckLabel.setText(_translate("Dialog", "Luck"))
        self.intelligenceLabel.setText(_translate("Dialog", "Intelligence"))
        self.enduranceLabel.setText(_translate("Dialog", "Endurance"))
        self.perceptionLabel.setText(_translate("Dialog", "Perception"))
        self.label_35.setText(_translate("Dialog", "Points to go"))
        self.speechLabel.setText(_translate("Dialog", "Speech"))
        self.unarmedLabel.setText(_translate("Dialog", "Unarmed"))
        self.repairLabel.setText(_translate("Dialog", "Repair"))
        self.throwingLabel.setText(_translate("Dialog", "Throwing"))
        self.pilotLabel.setText(_translate("Dialog", "Pilot"))
        self.gamblingLabel.setText(_translate("Dialog", "Gambling"))
        self.smallGunsLabel.setText(_translate("Dialog", "Small Guns"))
        self.bigGunsLabel.setText(_translate("Dialog", "Big Guns"))
        self.trapsLabel.setText(_translate("Dialog", "Traps"))
        self.barterLabel.setText(_translate("Dialog", "Barter"))
        self.explosivesLabel.setText(_translate("Dialog", "Explosives"))
        self.energyWeaponsLabel.setText(_translate("Dialog", "Energy Weapons"))
        self.sneakLabel.setText(_translate("Dialog", "Sneak"))
        self.meleeWeaponsLabel.setText(_translate("Dialog", "Melee Weapons"))
        self.lockpickLabel.setText(_translate("Dialog", "Lockpick"))
        self.survivalLabel.setText(_translate("Dialog", "Survival"))
        self.doctorLabel.setText(_translate("Dialog", "Doctor"))
        self.scienceLabel.setText(_translate("Dialog", "Science"))

